// *****************************************************************************
//
// This file is part of a MASA library or program.
// Refer to the included end-user license agreement for restrictions.
//
// Copyright (c) 2018 MASA Group
//
// *****************************************************************************

// *****************************************************************************
//    
// Warning: This file was generated by sof.generator.cpp Generator
// 
//*****************************************************************************

#ifndef ECORE_EOBJECT_HPP
#define ECORE_EOBJECT_HPP

#include "ecore/ENotifier.hpp"

#include <list>
#include <memory>
#include <string>
#include <boost/any.hpp>

//forward declarations
namespace ecore 
{
    template<typename T> class EList;
}

namespace ecore 
{
    class EClass;
}

namespace ecore 
{
    class EObject;
}

namespace ecore 
{
    class EOperation;
}

namespace ecore 
{
    class EReference;
}

namespace ecore 
{
    class EStructuralFeature;
}

// Start of user code forward declarations for EObject
namespace ecore
{
    class ENotificationChain;
}
// End of user code

namespace ecore 
{
    class EObject  : virtual public ecore::ENotifier
    {
        public:
            EObject(const EObject &) = delete;
            EObject& operator=(EObject const&) = delete;

        protected:
            EObject() = default;
     
        public:
            //destructor
            virtual ~EObject() = default;

            //*********************************
            // Operations
            //*********************************
            virtual std::shared_ptr<EList<std::shared_ptr<ecore::EObject>>> eAllContents() const = 0;
            
            virtual std::shared_ptr<ecore::EClass> eClass() const = 0;
            
            virtual std::shared_ptr<ecore::EObject> eContainer() const = 0;
            
            virtual std::shared_ptr<ecore::EStructuralFeature> eContainingFeature() const = 0;
            
            virtual std::shared_ptr<ecore::EReference> eContainmentFeature() const = 0;
            
            virtual std::shared_ptr<EList<std::shared_ptr<ecore::EObject>>> eContents() const = 0;
            
            virtual std::shared_ptr<EList<std::shared_ptr<ecore::EObject>>> eCrossReferences() const = 0;
            
            virtual boost::any eGet(const std::shared_ptr<ecore::EStructuralFeature>& feature) const = 0;
            
            virtual boost::any eGet(const std::shared_ptr<ecore::EStructuralFeature>& feature,bool resolve) const = 0;
            
            virtual boost::any eInvoke(const std::shared_ptr<ecore::EOperation>& operation,const std::shared_ptr<EList<boost::any>>& arguments) = 0;
            
            virtual bool eIsProxy() const = 0;
            
            virtual bool eIsSet(const std::shared_ptr<ecore::EStructuralFeature>& feature) const = 0;
            
            virtual int eResource() const = 0;
            
            virtual void eSet(const std::shared_ptr<ecore::EStructuralFeature>& feature,const boost::any& newValue) = 0;
            
            virtual void eUnset(const std::shared_ptr<ecore::EStructuralFeature>& feature) = 0;
            
            
            // Start of user code EObject
            virtual std::shared_ptr<ENotificationChain> eInverseAdd( const std::shared_ptr<EObject>& otherEnd
                                                                   , int featureID
                                                                   , const std::shared_ptr<ENotificationChain>& notifications ) = 0;
            virtual std::shared_ptr<ENotificationChain> eInverseRemove( const std::shared_ptr<EObject>& otherEnd
                                                                      , int featureID
                                                                      , const std::shared_ptr<ENotificationChain>& notifications ) = 0;
            // End of user code
    };
}
#endif /* ECORE_EOBJECT_HPP */
